export const exercisesList = [
  { name: "Vergence-I", code: "vergence1", type: "Binocular" },
  { name: "Perceive", code: "perceivemono", type: "Monocular" },
  { name: "Perceive", code: "perceivebino", type: "Binocular" },
  { name: "Recourse-II", code: "recoursemono2", type: "Monocular" },
  { name: "Recourse-II", code: "recoursebino2", type: "Binocular" },
  { name: "Glide-I", code: "glide1", type: "Binocular" },
  { name: "Glide-II", code: "glide2", type: "Binocular" },
  { name: "Glide-III", code: "glide3", type: "Monocular" },
  { name: "Glide-IV", code: "glide4", type: "Monocular" },
  { name: "Drub", code: "drubmono", type: "Monocular" },
  { name: "Drub", code: "drubbino", type: "Binocular" },
  { name: "Illustration-I", code: "illustration1", type: "Binocular" },
  { name: "Fleeting-I", code: "fleeting1", type: "Binocular" },
  { name: "Glance", code: "glancemono", type: "Monocular" },
  { name: "Glance", code: "glancebino", type: "Binocular" },
  { name: "Opt-I", code: "optmono1", type: "Monocular" },
  { name: "Opt-I", code: "optbino1", type: "Binocular" },
  { name: "Recourse-I (mono)", code: "recoursemono1", type: "Monocular" },
  { name: "Recourse-I (bino)", code: "recoursebino1", type: "Binocular" },
  { name: "Discover", code: "discover", type: "Monocular" },
  { name: "Direction-I", code: "direction1", type: "Binocular" },
  { name: "Direction-II", code: "direction2", type: "Binocular" },
  { name: "Direction-III", code: "direction3", type: "Binocular" },
  { name: "G-Discern-I", code: "gdiscerngabor1", type: "NeuroVision" },
  { name: "G-Discern-II", code: "gdiscerngabor2", type: "NeuroVision" },
  { name: "G-Flash-I", code: "gflashgabor1", type: "NeuroVision" },
  { name: "G-Flash-II", code: "gflashgabor2", type: "NeuroVision" },
  { name: "G-Identify", code: "gidentifygabor", type: "NeuroVision" },
  { name: "G-Locate", code: "glocategabor", type: "NeuroVision" },
  { name: "G-Pick-I", code: "gpickgabor1", type: "NeuroVision" },
  { name: "G-Pick-II", code: "gpickgabor2", type: "NeuroVision" },
  { name: "G-PinPoint", code: "gpinpointgabor", type: "NeuroVision" },
  { name: "W-Discern-I", code: "wdiscerngabor1", type: "NeuroVision" },
  { name: "W-Discern-II", code: "wdiscerngabor2", type: "NeuroVision" },
  { name: "W-Flash-I", code: "wflashgabor1", type: "NeuroVision" },
  { name: "W-Flash-II", code: "wflashgabor2", type: "NeuroVision" },
  { name: "W-Identify", code: "widentifygabor", type: "NeuroVision" },
  { name: "W-Locate", code: "wlocategabor", type: "NeuroVision" },
  { name: "W-Pick-I", code: "wpickgabor1", type: "NeuroVision" },
  { name: "W-Pick-II", code: "wpickgabor2", type: "NeuroVision" },
  { name: "W-PinPoint", code: "wpinpointgabor", type: "NeuroVision" },
  { name: "Ring Base-Out", code: "ringbaseout", type: "BaseInBaseOut" },
  { name: "Ring Base-In", code: "ringbasein", type: "BaseInBaseOut" },
  { name: "Ring Base-In-Out", code: "ringbaseinout", type: "BaseInBaseOut" },
  { name: "Square Base-Out", code: "squarebaseout", type: "BaseInBaseOut" },
  { name: "Square Base-In", code: "squarebasein", type: "BaseInBaseOut" },
  {
    name: "Square Base-In-Out",
    code: "squarebaseinout",
    type: "BaseInBaseOut",
  },
  { name: "Circle Base-Out", code: "circlebaseout", type: "BaseInBaseOut" },
  { name: "Circle Base-In", code: "circlebasein", type: "BaseInBaseOut" },
  {
    name: "Circle Base-In-Out",
    code: "circlebaseinout",
    type: "BaseInBaseOut",
  },
]
